name: absensi_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  provider: ^6.1.4
  shared_preferences: ^2.5.2
  bcrypt: ^1.1.3
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  fluttertoast: ^8.2.12
  lottie: ^3.3.1

  
  flutter_lints: ^5.0.0



flutter:

  
  uses-material-design: true

 
  assets:
    - assets/images/bg_screen3.jpg
    - assets/images/logo_app1.png
    - assets/images/lottie_logo1.json

  